# stages:
#   - build
#   - test
#   - deploy

# variables:
#   # Define environment variables for Cloudinary and MongoDB
#   CLOUDINARY_API_KEY: your_cloudinary_api_key
#   CLOUDINARY_API_SECRET: your_cloudinary_api_secret
#   MONGODB_URI: your_mongodb_uri

# # Define the Docker image name and tag
# image_name: my-python-app
# image_tag: latest

# # Build stage
# build:
#   stage: build
#   script:
#     - docker build -t $image_name:$image_tag .
#   only:
#     - master  # Only build on the master branch or other desired branches

# # Test stage (add your testing commands here)
# test:
#   stage: test
 
name: Merge to Master

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add build and test steps here

  merge_to_master:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge from main to Master
        run: |
          git config user.name "${{ secrets.GIT_USER_NAME }}"
          git config user.email "${{ secrets.GIT_USER_EMAIL }}"
          git checkout master
          git merge main --no-ff --no-edit
          git push origin master
