name: Merge to Master

on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  merge_to_master:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Git for fast-forward merges
        run: git config pull.ff only

      - name: Merge from main to Master
        run: |
          git config user.name "${{ secrets.GIT_USER_NAME }}"
          git config user.email "${{ secrets.GIT_USER_EMAIL }}"
          git checkout -b master
          git config pull.rebase false
          git pull origin master
          git merge main --allow-unrelated-histories
          git remote set-url origin https://github.com/vinhngo1907/module-uploader.git
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}